-- ============================================================
-- MIGRACIÓN: Guías de Remisión + Comprobantes de Retención
-- Ficha Técnica SRI v2.31 - Abril 2025
-- ============================================================

-- 1. TABLA: guias_remision
CREATE TABLE IF NOT EXISTS `guias_remision` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `usuario_id` int(11) NOT NULL,
  `empresa_id` int(11) NOT NULL,
  `punto_emision_id` int(11) NOT NULL,
  `cliente_id` int(11) NOT NULL,
  `comentarios` text DEFAULT NULL,
  `fecha_emision` datetime DEFAULT current_timestamp(),
  `fecha_ini_transporte` date NOT NULL,
  `fecha_fin_transporte` date DEFAULT NULL,
  `dir_partida` varchar(300) NOT NULL,
  `razon_social_transportista` varchar(300) DEFAULT NULL,
  `tipo_identificacion_transportista` varchar(2) DEFAULT NULL,
  `ruc_transportista` varchar(13) DEFAULT NULL,
  `placa` varchar(20) DEFAULT NULL,
  `identificacion_destinatario` varchar(13) NOT NULL,
  `razon_social_destinatario` varchar(300) NOT NULL,
  `dir_destinatario` varchar(300) DEFAULT NULL,
  `motivo_traslado` varchar(300) NOT NULL,
  `cod_estab_destino` varchar(3) DEFAULT NULL,
  `ruta` varchar(300) DEFAULT NULL,
  `cod_doc_sustento` varchar(2) NOT NULL DEFAULT '01',
  `num_doc_sustento` varchar(50) DEFAULT NULL,
  `num_aut_doc_sustento` varchar(49) DEFAULT NULL,
  `fecha_emision_doc_sustento` date DEFAULT NULL,
  `total` decimal(12,2) NOT NULL DEFAULT 0.00,
  `estado_xml` varchar(20) DEFAULT 'PENDIENTE',
  `clave_acceso` varchar(49) DEFAULT NULL,
  `xml_generado` tinyint(1) DEFAULT 0,
  `xml_firmado` tinyint(1) DEFAULT 0,
  `autorizado_sri` tinyint(1) DEFAULT 0,
  `archivo_xml` varchar(255) DEFAULT NULL,
  `numero_autorizacion` varchar(49) DEFAULT NULL,
  `fecha_autorizacion` datetime DEFAULT NULL,
  `observacion_sri` text DEFAULT NULL,
  `ambiente_id` int(11) NOT NULL DEFAULT 2,
  `establecimiento` int(11) NOT NULL,
  `punto_emision` int(11) NOT NULL,
  `secuencial` int(11) NOT NULL,
  `fecha_actualizacion` datetime DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_clave_acceso` (`clave_acceso`),
  KEY `idx_numero_autorizacion` (`numero_autorizacion`),
  KEY `empresa_id` (`empresa_id`),
  KEY `punto_emision_id` (`punto_emision_id`),
  KEY `usuario_id` (`usuario_id`),
  CONSTRAINT `fk_guia_usuario` FOREIGN KEY (`usuario_id`) REFERENCES `usuarios` (`id`),
  CONSTRAINT `fk_guia_empresa` FOREIGN KEY (`empresa_id`) REFERENCES `empresa` (`id`),
  CONSTRAINT `fk_guia_punto` FOREIGN KEY (`punto_emision_id`) REFERENCES `punto_emision` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

-- 2. TABLA: detalle_guia_remision
CREATE TABLE IF NOT EXISTS `detalle_guia_remision` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `guia_id` int(11) NOT NULL,
  `codigo_interno` varchar(50) DEFAULT '',
  `codigo_adicional` varchar(50) DEFAULT '',
  `descripcion` varchar(300) NOT NULL,
  `cantidad` decimal(12,4) NOT NULL DEFAULT 1.0000,
  PRIMARY KEY (`id`),
  KEY `guia_id` (`guia_id`),
  CONSTRAINT `fk_detalle_guia` FOREIGN KEY (`guia_id`) REFERENCES `guias_remision` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

-- 3. TABLA: comprobantes_retencion
CREATE TABLE IF NOT EXISTS `comprobantes_retencion` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `usuario_id` int(11) NOT NULL,
  `empresa_id` int(11) NOT NULL,
  `punto_emision_id` int(11) NOT NULL,
  `proveedor_id` int(11) DEFAULT NULL,
  `cliente_id` int(11) DEFAULT NULL,
  `comentarios` text DEFAULT NULL,
  `fecha_emision` datetime DEFAULT current_timestamp(),
  `tipo_identificacion_sujeto_retenido` varchar(2) NOT NULL,
  `razon_social_sujeto_retenido` varchar(300) NOT NULL,
  `identificacion_sujeto_retenido` varchar(13) NOT NULL,
  `periodo_fiscal` varchar(7) NOT NULL COMMENT 'mm/aaaa',
  `dir_establecimiento` varchar(300) DEFAULT NULL,
  `contribuyente_especial` varchar(50) DEFAULT NULL,
  `obligado_contabilidad` varchar(2) DEFAULT NULL,
  `total` decimal(12,2) NOT NULL DEFAULT 0.00,
  `estado_xml` varchar(20) DEFAULT 'PENDIENTE',
  `clave_acceso` varchar(49) DEFAULT NULL,
  `xml_generado` tinyint(1) DEFAULT 0,
  `xml_firmado` tinyint(1) DEFAULT 0,
  `autorizado_sri` tinyint(1) DEFAULT 0,
  `archivo_xml` varchar(255) DEFAULT NULL,
  `numero_autorizacion` varchar(49) DEFAULT NULL,
  `fecha_autorizacion` datetime DEFAULT NULL,
  `observacion_sri` text DEFAULT NULL,
  `ambiente_id` int(11) NOT NULL DEFAULT 2,
  `establecimiento` int(11) NOT NULL,
  `punto_emision` int(11) NOT NULL,
  `secuencial` int(11) NOT NULL,
  `fecha_actualizacion` datetime DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_clave_acceso` (`clave_acceso`),
  KEY `idx_numero_autorizacion` (`numero_autorizacion`),
  KEY `empresa_id` (`empresa_id`),
  KEY `punto_emision_id` (`punto_emision_id`),
  KEY `usuario_id` (`usuario_id`),
  KEY `proveedor_id` (`proveedor_id`),
  KEY `cliente_id` (`cliente_id`),
  CONSTRAINT `fk_retencion_usuario` FOREIGN KEY (`usuario_id`) REFERENCES `usuarios` (`id`),
  CONSTRAINT `fk_retencion_empresa` FOREIGN KEY (`empresa_id`) REFERENCES `empresa` (`id`),
  CONSTRAINT `fk_retencion_punto` FOREIGN KEY (`punto_emision_id`) REFERENCES `punto_emision` (`id`),
  CONSTRAINT `fk_retencion_proveedor` FOREIGN KEY (`proveedor_id`) REFERENCES `proveedores` (`id`),
  CONSTRAINT `fk_retencion_cliente` FOREIGN KEY (`cliente_id`) REFERENCES `clientes` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

-- 4. TABLA: detalle_retencion (impuestos retenidos por doc sustento)
CREATE TABLE IF NOT EXISTS `detalle_retencion` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `comprobante_retencion_id` int(11) NOT NULL,
  `cod_sustento` varchar(2) NOT NULL DEFAULT '01',
  `cod_doc_nr` varchar(2) NOT NULL DEFAULT '01' COMMENT 'Tipo comprobante retenido',
  `num_documento` varchar(50) NOT NULL,
  `fecha_emision_doc_sustento` date NOT NULL,
  `num_aut_documento` varchar(49) DEFAULT NULL,
  `fecha_autorizacion_doc_sustento` date DEFAULT NULL,
  `monto_total` decimal(12,2) NOT NULL,
  `pago_loc_ext` varchar(1) NOT NULL DEFAULT '01' COMMENT '01 local, 02 exterior',
  `total_sin_impuestos` decimal(12,2) NOT NULL,
  `cod_impuesto_doc_sustento` varchar(1) NOT NULL DEFAULT '1' COMMENT '1=IVA, 2=Renta, 3=ICE',
  `codigo_porcentaje` varchar(2) NOT NULL,
  `base_imponible` decimal(12,2) NOT NULL,
  `tarifa` decimal(5,2) NOT NULL,
  `valor_impuesto` decimal(12,2) NOT NULL,
  `codigo` varchar(1) NOT NULL COMMENT 'Tipo retención, 1=IVA, 2=Renta, 6=ISD',
  `codigo_retencion` varchar(10) NOT NULL,
  `porcentaje_retener` decimal(5,2) NOT NULL,
  `valor_retenido` decimal(12,2) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `comprobante_retencion_id` (`comprobante_retencion_id`),
  CONSTRAINT `fk_detalle_retencion` FOREIGN KEY (`comprobante_retencion_id`) REFERENCES `comprobantes_retencion` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

-- 5. TABLA: impuestos_retencion (catálogo de impuestos/porcentajes)
CREATE TABLE IF NOT EXISTS `impuestos_retencion` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `codigo` varchar(1) NOT NULL COMMENT '1=IVA, 2=Renta, 6=ISD',
  `codigo_retencion` varchar(10) NOT NULL,
  `descripcion` varchar(200) NOT NULL,
  `porcentaje` decimal(5,2) NOT NULL,
  `codigo_porcentaje_sri` varchar(2) DEFAULT NULL,
  `activo` tinyint(1) DEFAULT 1,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

-- Poblar catálogo de retenciones
INSERT INTO `impuestos_retencion` (`codigo`, `codigo_retencion`, `descripcion`, `porcentaje`, `codigo_porcentaje_sri`, `activo`) VALUES
('1', '1', 'Retención IVA 30%', 30.00, '2', 1),
('1', '2', 'Retención IVA 70%', 70.00, '3', 1),
('1', '3', 'Retención IVA 100%', 100.00, '10', 1),
('1', '4', 'Retención IVA 20%', 20.00, '1', 1),
('1', '6', 'Retención IVA 10%', 10.00, '10', 1),
('1', '7', 'Retención IVA 0%', 0.00, '0', 1),
('1', '8', 'No procede retención IVA', 0.00, '0', 1),
('2', '1', 'Renta 1%', 1.00, NULL, 1),
('2', '2', 'Renta 2%', 2.00, NULL, 1),
('2', '3', 'Renta 8%', 8.00, NULL, 1),
('2', '4', 'Renta 10%', 10.00, NULL, 1),
('2', '5', 'Renta 25%', 25.00, NULL, 1),
('2', '6', 'Renta 5%', 5.00, NULL, 1),
('2', '7', 'Renta 0%', 0.00, NULL, 1),
('2', '8', 'Renta 2.75%', 2.75, NULL, 1),
('2', '9', 'Renta 2% (combustibles)', 2.00, NULL, 1),
('2', '10', 'Renta 0.5% (combustibles)', 0.50, NULL, 1),
('6', '1', 'ISD 5%', 5.00, NULL, 1);
